[book]
title = "Sysand User Guide"
description = "Documentation for the Sysand CLI tool"
language = "en"

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/sensmetry/sysand"
