name: Javascript/WASM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 23

      - name: NPM install
        run: |
          cd bindings/js
          npm install

      - name: Prettier
        run: |
          cd bindings/js
          npm run prettier:check

      - name: ESLint
        run: |
          cd bindings/js
          npm run lint

      - name: Test in Firefox
        run: |
          cd bindings/js
          export WASM_BINDGEN_USE_BROWSER=1
          wasm-pack test --headless --firefox

      - name: Test in Chrome
        run: |
          cd bindings/js
          export WASM_BINDGEN_USE_BROWSER=1
          wasm-pack test --headless --chrome

      - name: Build for Node.js and test
        run: |
          cd bindings/js
          npm run test:browser
